version: '3.4'

services:
  identifier:
    container_name: kaleidos_backend
    image: semtech/mu-identifier:1.5.0
    links:
      - dispatcher:dispatcher
    ports:
      - "8082:80"
    networks:
      - proxy
      - default
      - backend
    environment:
      - VIRTUAL_HOST=kaleidos-backend.kanselarij-dev.s.redpencil.io
      - VIRTUAL_PORT=80
  dispatcher:
    image: semtech/mu-dispatcher:1.1.2
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config
  db:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.5.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    ports:
      - "8890:8890"
    volumes:
      - ./data/db:/data
  resource:
    image: semtech/mu-cl-resources:1.17.1
    links:
      - db:database
    volumes:
      - ./config/resources:/config
  file:
    image: semtech/mu-file-service:3.1.0
    links:
      - db:database
    volumes:
      - ./data/files:/share
  session-number-service:
    image: semtech/mu-javascript-template
    environment:
      NODE_ENV: "development"
    links:
      - db:database
    volumes:
      - ./session-number-service:/app
  agenda-sort-service:
    image: semtech/mu-javascript-template
    environment:
      NODE_ENV: "development"
    links:
      - db:database
    volumes:
      - ./agenda-sort-service:/app
  custom-subcases-service:
    image: semtech/mu-javascript-template
    environment:
      NODE_ENV: "development"
    links:
      - db:database
    volumes:
      - ./custom-subcases-service:/app
  agenda-approve-service:
    image: semtech/mu-javascript-template
    environment:
      NODE_ENV: "development"
    links:
      - db:database
    volumes:
      - ./agenda-approve-service:/app
  minister-jurisdiction-service:
    image: mikidi/mu-python-template:python3-port
    environment:
      MODE: "development"
    links:
      - db:database
    volumes:
      - ./minister-jurisdiction-service:/app
networks:
  backend:
    external: false
